### ISSUE TITLE
oauthSettings saved in localStorage

### ISSUE THREAD

**Issue by drupov** [niallmurphy-ie/drupal-react-oauth-provider#1]
Hi, I am playing around with the library and noticed that the oauthSettings, incl. clientID and clientSecret are stored and visible in the localStorage of the authenticated user. Should that work like that? Thanks

**Comment by niallmurphy-ie** [comment]
Hi, the client secret and ID are required for the refresh token. ~~However, this could be stored in a cookie instead for more security. I had considered the refresh token as safe since it is single use but perhaps everything should be cookie-based.~~

Edit: I don't think cookies this would be more secure as they wouldn't be set by the server.

**Comment by drupov** [comment]
Thanks for the reply and edit :)

Can we omit the storage and make sure to put them in e.g. environment variables instead?

EDIT: (I am simply not sure what the correct approach is for something like that, hence my question).

**Comment by niallmurphy-ie** [comment]
> Thanks for the reply and edit :)
> 
> Can we omit the storage and make sure to put them in e.g. environment variables instead?
> 
> EDIT: (I am simply not sure what the correct approach is for something like that, hence my question).

@drupov Well since you mentioned environmental variables, the best way to deal with this would be to have a small Express server running with the credentials stored there, with an option for setting that URL instead. Multiple URLs could exist for multiple clients. 

I hadn't considered this before but it is the correct solution. I'll create a server template / spec and make the adjustments required.

**Comment by niallmurphy-ie** [comment]
Hi @drupov 

I've added proxy support if you update to the latest version.

Docs: https://github.com/niallmurphy-ie/drupal-react-oauth-provider

Example frontend: https://github.com/niallmurphy-ie/drupal-react-oauth-provider-example/blob/master/src/App.tsx

Example proxy: https://github.com/niallmurphy-ie/drupal-react-oauth-provider-proxy-example/blob/master/index.js


Hopefully this is what you had in mind.
